---
name: Test workflow (test)

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    environment: test
    env:
      REDIS_URL: 'redis://localhost:6379'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Node 24
        uses: actions/setup-node@v2
        with:
          node-version: '24'

      - name: Run required containers
        run: docker compose -f docker-compose.test.yml up -d

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Run linter
        run: npm run format

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test
